### ISSUE TITLE
Issue with fixAgeGroup()?

### ISSUE THREAD

**Issue by yreecht** [casperwberg/surveyIndex#7]
Hi,

I was looking at the code of fixAgeGroup(), and it seems it is not doing exactly what its help says:

> The length of the [fake] individuals are set to the mean (or whatever 'fun' specifies) of all other individuals **of the same age**.

Indeed, it takes an object (d) with all ages together (at least according to the example in the help for getSurveyIdx() (https://github.com/casperwberg/surveyIndex/blob/master/surveyIndex/man/getSurveyIdx.Rd#L108-L111), and calculates the mean (or whatever...) of the lengths over all individuals, without subset on the age (https://github.com/casperwberg/surveyIndex/blob/0873d58f6a73be84a4f7bdb3b872de142dc8f992/surveyIndex/R/fixAgeGroup.R#L21C3-L21C41):

```{R}
subsLength=f(x[[3]]$LngtCm,na.rm=TRUE)
```
Looks to me this line should be something like:

```{R}
subsLength <- f(x[[1]]$LngtCm[x[[1]]$Age == age], na.rm=TRUE)
```
Or have I missed something?

Best wishes,
Yves

**Comment by casperwberg** [comment]
You are right, this is a bug.
It was not so much a problem if fun = min or max, but it has been fixed in
the latest commit.
Your proposed solution is not quite right though (because x[[3]] does not
have ages) so it is rather

subsLength <- f(x[[1]]$LngtCm[x[[1]]$Age == age], na.rm=TRUE)

Thanks for reporting this!



Den man. 22. jan. 2024 kl. 13.44 skrev Yves Reecht ***@***.***

**Comment by yreecht** [comment]
> Your proposed solution is not quite right though (because x[[3]] does not

Yes sorry, that was a typo in the original message, that I later corrected.
